name: flutter_sound
description: Local flutter_sound package with macOS/Linux/Windows stub implementations
version: 9.30.0
homepage: https://github.com/dooboolab/flutter_sound

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^1.0.0
  path_provider: ^2.1.2
  path: ^1.9.0
  synchronized: ^3.1.0
  logger: ^2.0.2
  flutter_sound_platform_interface: 9.30.0
  flutter_sound_web: 9.30.0

flutter:
  plugin:
    platforms:
      android:
        package: xyz.canardoux.fluttersound
        pluginClass: FlutterSound
      ios:
        pluginClass: FlutterSound
      macos:
        pluginClass: FlutterSoundPlugin
      linux:
        pluginClass: FlutterSoundPlugin
      windows:
        pluginClass: FlutterSoundPlugin
