name: ox_common
description: 0xChat common.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  build_runner: ^2.4.9
  isar_generator: ^3.1.0+1

  # third
  shared_preferences: ^2.0.5
  event_bus: ^2.0.0

  visibility_detector: ^0.3.3
  encrypt: ^5.0.3
  cached_network_image: 3.3.0
  package_info_plus: ^8.1.4
  pull_to_refresh: ^2.0.0
  lottie: ^3.1.3
  decimal: ^2.3.2
  json_annotation: ^4.8.0
  flutter_card_swipper : ^0.4.0
  permission_handler: ^11.0.0
  flutter_easyloading: ^3.0.0
  mobile_scanner: ^6.0.11
  archive: ^3.1.2
  fl_chart: ^0.35.0
  pretty_qr_code: ^2.0.2
  dart_ping: ^6.0.0
  dart_ping_ios: ^1.1.0
  lpinyin: ^2.0.0
  flutter_sticky_header: ^0.7.0
  syncfusion_flutter_core: '>=20.4.51 <20.4.52'
  syncfusion_flutter_sliders: '>=20.4.51 <20.4.52'
  html: ^0.15.0
  rive: ^0.13.20
  marquee: ^2.2.0
  flutter_slidable: ^4.0.0
  device_info_plus: ^11.3.0
  image_gallery_saver_plus:
    git:
      url: https://github.com/ArmanKT/image_gallery_saver_plus.git
      ref: master
  flutter_svg: ^2.0.4
  flutter_staggered_grid_view: ^0.6.1
  waterfall_flow: ^3.0.2
  extended_image: ^8.2.1
  quiver: ^3.1.0
  glassmorphism: ^3.0.0
  grouped_list: ^5.1.2
  rich_text_widget: ^0.2.7
  modal_bottom_sheet: ^3.0.0-pre
  roundcheckbox: ^2.0.4+1
  simple_gradient_text: ^1.2.4
  sticky_headers: ^0.3.0+2
  in_app_purchase: ^3.2.1
  sliver_header_delegate: ^0.0.5
  extended_sliver: ^2.1.3
  flutter_vibrate: ^1.3.0
  webview_flutter: ^4.10.0
  flutter_oss_aliyun: ^6.2.5
  photo_view: ^0.14.0
  url_launcher: ^6.0.0
  audioplayers: ^6.0.0
  local_auth: ^2.3.0
  pick_or_save: ^2.2.4
  audio_session: ^0.1.18
  easy_loading_button: ^0.3.2
  file_picker: ^9.0.0
  share_plus: ^10.1.4
  animated_text_kit: ^4.2.2
  video_thumbnail: ^0.5.3
  chewie: ^1.4.0  #Player
  minio:
    path: ./minio
  bitsdojo_window: ^0.1.6
  screenshot: ^3.0.0
  emoji_picker_flutter: 1.5.4
  window_manager: ^0.4.3
  fc_native_video_thumbnail: ^0.17.2

  chatcore:
    path: ../../0xchat-core
  cashu_dart:
    path: ../../cashu-dart
  ox_cache_manager:
    path: ../ox_cache_manager
  ox_theme:
    path: ../ox_theme
  ox_module_service:
    path: ../ox_module_service
  ox_localizable:
    path: ../ox_localizable
  ox_network:
    path: ../ox_network

#  chatcore:
#    git:
#      url: https://github.com/wkuangji/0xchat-core

#dependency_overrides:
#    pull_to_refresh:
#      git:
#        url: https://github.com/miquelbeltran/flutter_pulltorefresh
#        ref: master



dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.6
  json_serializable: ^6.5.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the Icons class.
  uses-material-design: true
  assets:
    - assets/theme/
    - assets/images/
    - assets/images/dark/
    - assets/images/light/
    - assets/locale/
    - assets/dark/
    - assets/light/



  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.ox.ox_common
        pluginClass: OXCommonPlugin
      ios:
        pluginClass: OXCCommonPlugin
      macos:
        pluginClass: OXCCommonPlugin

  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
